name: Tests
on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: "build: checkout the latest changes"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: "build: install the required dependencies"
      run: npm ci

    - name: "build: package the latest changes"
      run: npm run build

    - name: "unit(test): perform unit test checks"
      run: npm test

   