name: Local run

# Requires mocking the "public" event to begin this workflow and avoid actual runs
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  public:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
    - name: Build action
      run: npm install && npm run build
    - name: upload a file
      id: mminio
      uses: ./.
      with:
        endpoint: '192.168.219.100'
        port: 9000
        file: '/test.txt'
      env:
        MINIO_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        MINIO_ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}